# Project Information
site_name: XDU-WiKi
site_description: 为西电本科生制作的维基网站
site_author: InsightsXDU
site_url: https://InsightsXDU.github.io/XDU-WiKi/
strict: false

# Repository
repo_name: "InsightsXDU/XDU-WiKi"
repo_url: "https://github.com/InsightsXDU/XDU-WiKi"



# Contents
nav:
    - 开始:
          - 欢迎: index.md
          - 路线分享: 
              - 序言: 开始/路线分享序言.md
    - 生活: 
          - 序言: 生活/序言.md
    - 在校学习指南:
          - 基础学科: 在校学习指南/基础学科/序言.md
          - CV方向: 在校学习指南/CV方向/序言.md
          - NLP方向: 在校学习指南/NLP方向/序言.md
          - 前端: 在校学习指南/前端/序言.md
          - 后端: 
              - 序言: 在校学习指南/后端/序言.md
    - 社团与工作室们: 
          - 序言: 社团与工作室们/序言.md
    - 保研: 
          - 序言: 保研/序言.md
    - 考研: 
          - 序言: 考研/序言.md
    - 工作: 
          - 序言: 工作/序言.md
    - 参与贡献:
          - 如何贡献: 参与贡献/如何贡献.md
          - 项目结构: 参与贡献/项目结构.md
    - 关于 Datawhale: https://datawhale.club/

theme:
    name: material
    logo: images/test.png
    palette:
        - scheme: default # 日间模式
          primary: white # 上方的
          accent: red # 链接等可交互元件的高亮色
          toggle:
              icon: material/weather-night # 图标
              name: 切换至夜间模式 # 鼠标悬浮提示
        - scheme: slate # 夜间模式
          primary: black
          accent: yellow
          toggle:
              icon: material/weather-sunny
              name: 切换至日间模式
    features:
        - navigation.instant #- header.autohide  #自动隐藏
        - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
        - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
        - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
        - navigation.top # 返回顶部的按钮 在上滑时出现
        - search.suggest # 搜索输入一些字母时推荐补全整个单词
        - search.highlight # 搜索出的文章关键词加入高亮
        - content.code.copy # 代码块右侧复制到剪切板
        #- navigation.expand # 打开Tab时左侧目录全部展开
    language: zh # 一些提示性的文字会变成中文

extra:
    generator: false

plugins:
    - search
    - tags #标签
    - glightbox
    - mkdocs-jupyter
markdown_extensions:
    - abbr
    - pymdownx.arithmatex: # MathJax 支持
          generic: true
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - toc:
          permalink: true # 固定标题位置为当前位置
    - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          #auto_title: true # 显示编程语言名称
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences # 代码高亮支持
    - tables
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - pymdownx.details

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js